/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.modaoperandi.java.jwt.tools;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
